### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by KimYangOfCat** [chenjie04/LSPM#1]
Thank you very much for sharing the source code of this paper~
But after reading your source code, I encountered some problems and hope to get your help ~
It seems that **your source code does not describe the environment version of your source code implementation**, which brings us some difficulties in reproducing. can you add a source environment description document?  Then we can learn your experiment better ~
Thanks~

**Comment by chenjie04** [comment]
Sorry for the late reply, and we have made some updates about our code, including the requirements of the environment.
